name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout repo
      - uses: actions/checkout@v6

      # Create folder for SVGs if it doesn't exist
      - run: mkdir -p profile

      # Generate stats card
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=VukasinStankovic&show_icons=true&count_private=true&theme=gotham
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate top languages card
      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=VukasinStankovic&layout=compact&langs_count=6&theme=gotham
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Generate pinned repo card
      - name: Generate pinned repo card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=VukasinStankovic&repo=VukasinStankovic&theme=gotham
          path: profile/pin-my-repo.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Commit and push generated SVGs
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
